package com.causa.infrastructure.persistence.entity;

import com.causa.common.constants.ConfigConstants.PlatformCategory;
import com.fasterxml.jackson.databind.JsonNode;
import jakarta.persistence.*;
import org.hibernate.annotations.JdbcTypeCode;
import org.hibernate.type.SqlTypes;

/**
 * JPA Entity for the {@code external_configs} table.
 *
 * <p>Covers both Observability (DATADOG / INSTANA) and Integration
 * (SLACK / JIRA / GITHUB) configs using a {@code category} discriminator column.
 * UNIQUE(platform, name) — multiple named configs per platform allowed.
 *
 * <p>ID convention: {@code ext_cnf_<16-char-alphanumeric>} — generated by
 * {@link com.causa.common.utils.IdUtils#generateExternalConfigId()}.
 *
 * @since 0.0.3
 */
@Entity
@Table(
    name = "external_configs",
    uniqueConstraints = @UniqueConstraint(
        name = "uq_external_configs_plat_name",
        columnNames = {"platform", "name"}
    )
)
public class ExternalConfigEntity extends BaseEntity {

    /** Application-generated PK: {@code ext_cnf_<16-char-alphanumeric>}. Total length = 24 chars. */
    @Id
    @Column(nullable = false, length = 24)
    private String id;

    /** OBSERVABILITY or INTEGRATION. */
    @Enumerated(EnumType.STRING)
    @Column(nullable = false, length = 32)
    private PlatformCategory category;

    /**
     * Platform name — plain String because the same column holds values from two enum types
     * ({@code ObservabilityPlatform} / {@code IntegrationPlatform}); resolved by the service layer.
     */
    @Column(nullable = false, length = 64)
    private String platform;

    /** User-defined label for this config (e.g. {@code instana-prod}). Part of the unique key with platform. */
    @Column(nullable = false, length = 128)
    private String name;

    /** Platform endpoint / base URL. Nullable. */
    @Column(columnDefinition = "TEXT")
    private String url;

    /** Whether this platform config is active. Defaults to {@code true}. */
    @Column(nullable = false)
    private Boolean isActive = true;

    /** Credentials JSONB. Sensitive fields AES-256-GCM encrypted. NOT NULL. */
    @JdbcTypeCode(SqlTypes.JSON)
    @Column(nullable = false, columnDefinition = "jsonb")
    private JsonNode authConfig;

    /** Free-form JSONB for platform-specific behavioural fields (channel, projectName, etc.). */
    @JdbcTypeCode(SqlTypes.JSON)
    @Column(columnDefinition = "jsonb")
    private JsonNode additionalConfig;

    // -------------------------------------------------------------------------
    // Getters and Setters
    // -------------------------------------------------------------------------

    public String getId() { return id; }
    public void setId(String id) { this.id = id; }

    public PlatformCategory getCategory() { return category; }
    public void setCategory(PlatformCategory category) { this.category = category; }

    public String getPlatform() { return platform; }
    public void setPlatform(String platform) { this.platform = platform; }

    public String getName() { return name; }
    public void setName(String name) { this.name = name; }

    public String getUrl() { return url; }
    public void setUrl(String url) { this.url = url; }

    public Boolean getIsActive() { return isActive; }
    public void setIsActive(Boolean isActive) { this.isActive = isActive; }

    public JsonNode getAuthConfig() { return authConfig; }
    public void setAuthConfig(JsonNode authConfig) { this.authConfig = authConfig; }

    public JsonNode getAdditionalConfig() { return additionalConfig; }
    public void setAdditionalConfig(JsonNode additionalConfig) { this.additionalConfig = additionalConfig; }
}
