package com.causa.infrastructure.persistence.entity;

import com.causa.common.constants.ConfigConstants.LlmProvider;
import com.fasterxml.jackson.databind.JsonNode;
import jakarta.persistence.*;
import org.hibernate.annotations.JdbcTypeCode;
import org.hibernate.type.SqlTypes;

import java.math.BigDecimal;

/**
 * JPA Entity for the {@code llm_configs} table.
 *
 * <p>One row per LLM provider (UNIQUE on {@code provider}). At most one row may have
 * {@code is_active = true} — this invariant is enforced by the service layer.
 *
 * <p>ID convention: {@code llm_cnf_<16-char-alphanumeric>} — generated by
 * {@link com.causa.common.utils.IdUtils#generateLlmConfigId()}.
 *
 * @since 0.0.3
 */
@Entity
@Table(
    name = "llm_configs",
    uniqueConstraints = @UniqueConstraint(
        name = "uq_llm_configs_prov",
        columnNames = {"provider"}
    )
)
public class LlmConfigEntity extends BaseEntity {

    /** Application-generated PK: {@code llm_cnf_<16-char-alphanumeric>}. Total length = 24 chars. */
    @Id
    @Column(nullable = false, length = 24)
    private String id;

    /** OPENAI | ANTHROPIC | AZURE_OPENAI | WATSONX. */
    @Enumerated(EnumType.STRING)
    @Column(nullable = false, length = 64)
    private LlmProvider provider;

    /** LLM API endpoint URL. NOT NULL. */
    @Column(nullable = false, columnDefinition = "TEXT")
    private String url;

    /** Available model identifiers for this provider (e.g. {@code {gpt-4o, gpt-4o-mini}}). NOT NULL. */
    @Column(nullable = false, columnDefinition = "TEXT[]")
    private String[] models;

    /** Sampling temperature. Nullable — falls back to model default. */
    @Column(precision = 4, scale = 2)
    private BigDecimal temperature;

    /** Max output tokens. Nullable — falls back to model default. */
    @Column
    private Integer maxTokens;

    /** Request timeout in milliseconds. Nullable — falls back to client default. */
    @Column
    private Integer timeoutMs;

    /** Whether this provider is used by the analysis engine. At most one row is true. */
    @Column(nullable = false)
    private Boolean isActive = true;

    /** Credentials JSONB. Sensitive fields AES-256-GCM encrypted. NOT NULL. */
    @JdbcTypeCode(SqlTypes.JSON)
    @Column(nullable = false, columnDefinition = "jsonb")
    private JsonNode authConfig;

    /** Free-form JSONB for future provider-specific fields. */
    @JdbcTypeCode(SqlTypes.JSON)
    @Column(columnDefinition = "jsonb")
    private JsonNode additionalConfig;

    // -------------------------------------------------------------------------
    // Getters and Setters
    // -------------------------------------------------------------------------

    public String getId() { return id; }
    public void setId(String id) { this.id = id; }

    public LlmProvider getProvider() { return provider; }
    public void setProvider(LlmProvider provider) { this.provider = provider; }

    public String getUrl() { return url; }
    public void setUrl(String url) { this.url = url; }

    public String[] getModels() { return models; }
    public void setModels(String[] models) { this.models = models; }

    public BigDecimal getTemperature() { return temperature; }
    public void setTemperature(BigDecimal temperature) { this.temperature = temperature; }

    public Integer getMaxTokens() { return maxTokens; }
    public void setMaxTokens(Integer maxTokens) { this.maxTokens = maxTokens; }

    public Integer getTimeoutMs() { return timeoutMs; }
    public void setTimeoutMs(Integer timeoutMs) { this.timeoutMs = timeoutMs; }

    public Boolean getIsActive() { return isActive; }
    public void setIsActive(Boolean isActive) { this.isActive = isActive; }

    public JsonNode getAuthConfig() { return authConfig; }
    public void setAuthConfig(JsonNode authConfig) { this.authConfig = authConfig; }

    public JsonNode getAdditionalConfig() { return additionalConfig; }
    public void setAdditionalConfig(JsonNode additionalConfig) { this.additionalConfig = additionalConfig; }
}
